language: python
sudo: required

python:
  - '3.6'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - git clone --depth=1 https://github.com/ioi/isolate.git
    && cd isolate
    && make PREFIX="/usr" VARPREFIX="/var" CONFIGDIR="/etc" isolate
    && sudo PREFIX="/usr" VARPREFIX="/var" CONFIGDIR="/etc" install
    && sudo sed -i "s|/var/local/lib/isolate|/var/lib/isolate|" /etc/isolate
    && sudo chown $USER:root /usr/bin/isolate
    && sudo chmod u=rx,g=rwxs,o= /usr/bin/isolate

script:
  - isolate --box-id 1 --cg --init
    && ls /var/lib/isolate
  - isolate --box-id 1 --cleanup
    && ls /var/lib/isolate
