language: python
sudo: required

python:
  - '3.6'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - git clone --depth=1 https://github.com/ioi/isolate.git
    && cd isolate
    &&      make PREFIX="/usr" VARPREFIX="/var" CONFIGDIR="/etc" isolate
    && sudo make PREFIX="/usr" VARPREFIX="/var" CONFIGDIR="/etc" install
    && sudo sed -i "s|/var/local/lib/isolate|/var/lib/isolate|" /etc/isolate
    && sudo groupadd isolate
    && sudo usermod -a -G isolate $USER
    && sudo chown -v root:isolate /usr/bin/isolate
    && sudo chmod -v u+s /usr/bin/isolate
    && ls -l  /usr/bin/isolate
    && ls -ln /usr/bin/isolate
    && newgrp isolate
    && id

script:
  - newgrp isolate && id
  - isolate --box-id 1 --cg --init
    && ls /var/lib/isolate
  - isolate --box-id 1 --cleanup
    && ls /var/lib/isolate
